spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:  
    url: jdbc:mysql://localhost:3306/mytables
    username: root
    password: root123
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   hibernate:
     ddl-auto: update
    
app: 
   properties: 
    succMsg: Book Stored Successfully....
    failMsg: Book Not stored please tray again
    
     
##Data Base Configurations
#spring: 
#  datasource:
#    url: jdbc:mysql://localhost:3306/mytables
#    username: root
#    password: root123
#    driver-class-name: "com.mysql.jdbc.Driver"
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update